@startuml

class GridParameters {
    string filename
    list [float] dia_pos0
    list [float] dia_pos1

    list [int] gridSize
    dict layer
    list [Pad] pad_obstacles
    dict [str, NetClass] netClassList
    int netNum
    list [Net] netList

    list to_real_coord(grid_coord)
    void store_route(merge_route_combo)
}

class Net {
    int netID
    string netName
    string netClass
    list [Pad] padList
}

class Pad {
    list [int] position
    string layer
    list [int] size
    string type
    int netID
}

class NetClass {
    int track_width
    int microvia_diameter
    int microvia_drill
}

Net "1" o-right- "n" Pad
GridParameters "1" o-down- "m" Net
GridParameters "1" o-right- "p" Pad
GridParameters "1" o-right- "q" NetClass

@enduml